[build]
base = ""
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = "dist/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200